"""Texts only the Android app shows (settings, history, about).

The download texts shared with the Windows app come from ``locales/`` via
:func:`i18n.tr`. These Android-only texts exist in English and Turkish;
every other language shows the English ones.
"""

import i18n

TEXTS = {
    "en": {
        "nav.home": "Download",
        "nav.history": "History",
        "nav.settings": "Settings",
        "home.link_hint": "Paste or share a link",
        "home.clear": "Clear",
        "home.mode": "Download as",
        "home.video": "Video",
        "home.audio": "Audio",
        "home.quality": "Quality",
        "home.format": "Format",
        "home.trim": "Only part of it",
        "home.trim_hint": "e.g. 1:30",
        "home.details": "Details",
        "home.hide_details": "Hide details",
        "home.saved": "Saved to {folder}",
        "home.open": "Open",
        "home.shared": "Link received",
        "home.no_trim_playlist": "Trimming works on single videos, not playlists",
        "home.tiktok": "TikTok support",
        "history.empty": "Your downloads will show up here.",
        "history.clear": "Clear history",
        "history.clear_body": "Remove every entry from the history? The files stay on your phone.",
        "history.missing": "The file was moved or deleted",
        "history.open_failed": "No app could open this file",
        "history.share": "Share",
        "history.delete": "Remove from history",
        "settings.appearance": "Appearance",
        "settings.theme": "Theme",
        "settings.dynamic": "Colours from wallpaper",
        "settings.dynamic_hint": "Material You, Android 12 and newer",
        "settings.accent": "Accent colour",
        "settings.accent_hint": "Used when wallpaper colours are off",
        "settings.language": "Language",
        "settings.downloads": "Downloads",
        "settings.default_mode": "Start with",
        "settings.video_quality": "Video quality",
        "settings.video_container": "Video format",
        "settings.audio_format": "Audio format",
        "settings.audio_quality": "Audio quality",
        "settings.fragments": "Parallel connections",
        "settings.fragments_hint": "{count} at once. More is faster on streamed videos (Instagram, X, live); lower it on a weak connection.",
        "settings.folder": "Save to",
        "settings.behaviour": "Behaviour",
        "settings.auto_paste": "Paste links automatically",
        "settings.auto_paste_hint": "Take a link from the clipboard when you open the app",
        "settings.auto_analyze": "Analyze shared links at once",
        "settings.auto_analyze_hint": "When you share a link from another app",
        "settings.keep_screen": "Keep the screen on",
        "settings.keep_screen_hint": "While a download runs",
        "settings.history": "Keep a download history",
        "settings.about": "About",
        "settings.version": "Version",
        "settings.whats_new": "What's new",
        "settings.components": "Components",
        "settings.diagnostics": "Copy diagnostic log",
        "settings.diagnostics_hint": "The app's recent Android log, to send to the developer",
        "settings.reset": "Reset settings",
        "settings.reset_body": "Put every setting back to its default?",
        "settings.reset_done": "Settings reset",
        "theme.system": "System",
        "theme.light": "Light",
        "theme.dark": "Dark",
        "accent.Blue": "Blue",
        "accent.Teal": "Teal",
        "accent.Green": "Green",
        "accent.Purple": "Purple",
        "accent.Pink": "Pink",
        "accent.Red": "Red",
        "accent.Orange": "Orange",
        "accent.Indigo": "Indigo",
        "common.on": "On",
        "common.off": "Off",
        "common.available": "available",
        "common.missing": "not available",
        "common.cancel": "Cancel",
        "common.ok": "OK",
        "common.close": "Close",
        "common.remove": "Remove",
        "common.reset": "Reset",
        "crash.title": "Something went wrong last time",
        "crash.body": "The app closed unexpectedly. Copying this report and sending it to the developer helps fix it.",
        "crash.copy": "Copy report",
        "crash.copied": "Report copied",
        "crash.error": "Something went wrong: {error}",
        "youtube.section": "YouTube",
        "youtube.sign_in": "Sign in to YouTube",
        "youtube.sign_in_hint": "Optional. Only if YouTube keeps asking to confirm you're not a bot. The sign-in stays on this phone.",
        "youtube.signed_in": "Signed in to YouTube",
        "youtube.sign_out_hint": "Tap to sign out",
        "youtube.sign_out": "Sign out",
        "youtube.done": "Done",
        "youtube.bot_title": "YouTube blocks this network",
        "youtube.bot_body": "YouTube takes requests from this network for a bot, even through the phone's browser engine. Try again on Wi-Fi or another network. If nothing else helps, signing in under Settings \u203a YouTube also fixes it.",
        "youtube.ok_button": "OK",
        "youtube.via_browser": "YouTube asked to confirm this is not a bot; trying again through the phone's browser engine",
        "youtube.browser_count": "YouTube answered through the phone's browser engine ({count} requests)",
        "youtube.ok": "Signed in to YouTube",
        "youtube.failed": "Not signed in; nothing was saved",
        "youtube.signed_out": "Signed out of YouTube",
    },
    "tr": {
        "nav.home": "İndir",
        "nav.history": "Geçmiş",
        "nav.settings": "Ayarlar",
        "home.link_hint": "Bir bağlantı yapıştırın veya paylaşın",
        "home.clear": "Temizle",
        "home.mode": "İndirme türü",
        "home.video": "Video",
        "home.audio": "Ses",
        "home.quality": "Kalite",
        "home.format": "Biçim",
        "home.trim": "Yalnızca bir kısmı",
        "home.trim_hint": "ör. 1:30",
        "home.details": "Ayrıntılar",
        "home.hide_details": "Ayrıntıları gizle",
        "home.saved": "{folder} klasörüne kaydedildi",
        "home.open": "Aç",
        "home.shared": "Bağlantı alındı",
        "home.no_trim_playlist": "Kırpma oynatma listelerinde değil, tek videolarda çalışır",
        "home.tiktok": "TikTok desteği",
        "history.empty": "İndirdikleriniz burada görünecek.",
        "history.clear": "Geçmişi temizle",
        "history.clear_body": "Geçmişteki tüm kayıtlar silinsin mi? Dosyalar telefonunuzda kalır.",
        "history.missing": "Dosya taşınmış veya silinmiş",
        "history.open_failed": "Bu dosyayı açabilecek bir uygulama yok",
        "history.share": "Paylaş",
        "history.delete": "Geçmişten kaldır",
        "settings.appearance": "Görünüm",
        "settings.theme": "Tema",
        "settings.dynamic": "Duvar kağıdı renkleri",
        "settings.dynamic_hint": "Material You, Android 12 ve üstü",
        "settings.accent": "Vurgu rengi",
        "settings.accent_hint": "Duvar kağıdı renkleri kapalıyken kullanılır",
        "settings.language": "Dil",
        "settings.downloads": "İndirmeler",
        "settings.default_mode": "Varsayılan tür",
        "settings.video_quality": "Video kalitesi",
        "settings.video_container": "Video biçimi",
        "settings.audio_format": "Ses biçimi",
        "settings.audio_quality": "Ses kalitesi",
        "settings.fragments": "Paralel bağlantı",
        "settings.fragments_hint": "Aynı anda {count}. Parça parça gelen videolarda (Instagram, X, canlı yayın) çok olması hızlandırır; zayıf bağlantıda azaltın.",
        "settings.folder": "Kayıt yeri",
        "settings.behaviour": "Davranış",
        "settings.auto_paste": "Bağlantıyı otomatik yapıştır",
        "settings.auto_paste_hint": "Uygulama açılınca panodaki bağlantıyı al",
        "settings.auto_analyze": "Paylaşılan bağlantıyı hemen incele",
        "settings.auto_analyze_hint": "Başka bir uygulamadan bağlantı paylaştığınızda",
        "settings.keep_screen": "Ekranı açık tut",
        "settings.keep_screen_hint": "İndirme sürerken",
        "settings.history": "İndirme geçmişini tut",
        "settings.about": "Hakkında",
        "settings.version": "Sürüm",
        "settings.whats_new": "Yenilikler",
        "settings.components": "Bileşenler",
        "settings.diagnostics": "Tanılama kaydını kopyala",
        "settings.diagnostics_hint": "Uygulamanın son Android kaydı, geliştiriciye göndermek için",
        "settings.reset": "Ayarları sıfırla",
        "settings.reset_body": "Tüm ayarlar varsayılana dönsün mü?",
        "settings.reset_done": "Ayarlar sıfırlandı",
        "theme.system": "Sistem",
        "theme.light": "Aydınlık",
        "theme.dark": "Karanlık",
        "accent.Blue": "Mavi",
        "accent.Teal": "Camgöbeği",
        "accent.Green": "Yeşil",
        "accent.Purple": "Mor",
        "accent.Pink": "Pembe",
        "accent.Red": "Kırmızı",
        "accent.Orange": "Turuncu",
        "accent.Indigo": "Çivit",
        "common.on": "Açık",
        "common.off": "Kapalı",
        "common.available": "var",
        "common.missing": "yok",
        "common.cancel": "Vazgeç",
        "common.ok": "Tamam",
        "common.close": "Kapat",
        "common.remove": "Kaldır",
        "common.reset": "Sıfırla",
        "crash.title": "Geçen sefer bir sorun oldu",
        "crash.body": "Uygulama beklenmedik şekilde kapandı. Bu raporu kopyalayıp geliştiriciye göndermeniz düzeltmeye yardımcı olur.",
        "crash.copy": "Raporu kopyala",
        "crash.copied": "Rapor kopyalandı",
        "crash.error": "Bir sorun oldu: {error}",
        "youtube.section": "YouTube",
        "youtube.sign_in": "YouTube'a giriş yap",
        "youtube.sign_in_hint": "İsteğe bağlı. Yalnızca YouTube bot doğrulamasını istemeye devam ederse. Giriş yalnızca bu telefonda kalır.",
        "youtube.signed_in": "YouTube'a giriş yapıldı",
        "youtube.sign_out_hint": "Çıkış yapmak için dokunun",
        "youtube.sign_out": "Çıkış yap",
        "youtube.done": "Bitti",
        "youtube.bot_title": "YouTube bu ağı engelliyor",
        "youtube.bot_body": "YouTube bu ağdan gelen istekleri, telefonun tarayıcı motoru üzerinden bile bot sanıyor. Wi-Fi ya da başka bir ağla yeniden deneyin. Hiçbiri olmazsa Ayarlar \u203a YouTube'dan giriş yapmak da çözer.",
        "youtube.ok_button": "Tamam",
        "youtube.via_browser": "YouTube bot doğrulaması istedi; telefonun tarayıcı motoru üzerinden yeniden deneniyor",
        "youtube.browser_count": "YouTube telefonun tarayıcı motoru üzerinden yanıt verdi ({count} istek)",
        "youtube.ok": "YouTube'a giriş yapıldı",
        "youtube.failed": "Giriş yapılmadı; hiçbir şey kaydedilmedi",
        "youtube.signed_out": "YouTube'dan çıkış yapıldı",
    },
}


def t(key, **values):
    """Android-only text in the current language, else English, else the shared catalog."""
    text = TEXTS.get(i18n.current(), {}).get(key) or TEXTS["en"].get(key)
    if text is None:
        return i18n.tr(key, **values)
    return text.format(**values) if values else text
